language: ruby
sudo: false
install: bundle install --without development --jobs=3 --retry=3
cache: bundler
branches:
  only:
  - build
before_script:
- mkdir build
script:
- bundle exec jekyll build
deploy:
  fqdn: www.morozov.is
  local_dir: build
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: false
  target-branch: master
  on:
    branch: build

