language: ruby
sudo: false
install:
  - gem install bundler -v '1.17.3'
  - bundle install --without development --jobs=3 --retry=3
cache: bundler
branches:
  except:
    - master
before_script:
  - mkdir build
script:
  - bundle exec jekyll build
  - bundle exec danger
deploy:
  fqdn: www.morozov.is
  local_dir: _site
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: false
  target-branch: master
  on:
    branch: build
