# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Igor writing about things"
name: Igor Morozov
email: igor@morozov.is
repository: Morozzzko/Morozzzko.github.io
description: |
  Thoughts, programming, Ruby

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.morozov.is" # the base hostname & protocol for your site, e.g. http://example.com

collections:
  slides:
    output: true
    permalink: /:collection/:name

read_time: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-include-cache

kramdown:
  toc_levels: 1..3

theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "dirt" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"

paginate: 5

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: false

excerpt_separator: "<!-- excerpt -->"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

author:
  name: Igor Morozov
  avatar: "/assets/images/bio-photo.jpg"
  bio: |
    I'm a software engineer familiar with Ruby, Python, JavaScript and ReasonML.
    <br />
    I'm enthusiastic about functional programming, Ruby, DDD and emotions.
    <br />
    I'm not much of a Rails person. dry-rb, mostly.
  email: igor@morozov.is
  home: / # null (default), "absolute or relative url to link to author home"
  github: Morozzzko
  linkedin: igor-morozov
  twitter: morozzzko
